from .user import User
from .major import Major
from .majorDirection import MajorDirection
from .course import Course
from .teacher import Teacher
from .classroom import Classroom
from .department import Department
from .scheduleTask import ScheduleTask
from .teachingBuilding import TeachingBuilding
from .verificationCode import VerificationCode
from .classInfo import Class